name: GitHub Actions Build and Deploy VSCode Snippets
on:
  push:
    branches: ['**']
    tags: [v*]
  pull_request:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      
      - name: Install yarn
        run: npm install -g yarn

      - name: Install the dependencies
        run: yarn install --frozen-lockfile

      - name: Install vsce
        run: npm i -g vsce

      - name: vsce login
        run: vsce login ${{ secrets.VSCE_ACCOUNT }}
      
      - name: Publish
        run: vsce publish patch -p ${{ secrets.VSCE_PAT }}